security:
  oauth2:
    client:
      clientId: 2329978113899780
      clientSecret: 2a001f23338d0f2220c67fe96a05ca95
      accessTokenUri: https://developers.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      appId: 2329978113899780
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG